# Generated by Django 3.2.2 on 2021-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
