# Generated by Django 3.2.2 on 2021-05-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_photo_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='ratio',
        ),
    ]
